name: 'Analogicus Janeway Documentation Action'
description: 'This action generates jekyll docs'
branding:
  color: purple
  icon: layers

runs:
    using: 'composite'
    steps:
      #- name: Install PDK
      #  shell: bash
      #  run: |
      #    export PDK_ROOT=/opt/pdk/share/pdk
      #    cd $HOME
      #    git clone https://github.com/RTimothyEdwards/open_pdks.git
      #    cd open_pdks
      #    ./configure --prefix=/opt/pdk --enable-sky130-pdk --with-sky130-variants=A \
      #      --enable-primitive-sky130 --enable-sc-hd-sky130 \
      #      --disable-io-sky130 --disable-sc-hs-sky130 --disable-sc-ms-sky130 --disable-sc-ls-sky130 \
      #      --disable-sc-lp-sky130 --disable-sc-hdll-sky130 --disable-sc-hvl-sky130 --disable-alpha-sky130 \
      #      --disable-xschem-sky130 \
      #      --disable-gf180mcu-pdk --disable-primitive-gf180mcu \
      #      --disable-verification-gf180mcu --disable-klayout-gf180mcu --disable-io-gf180mcu \
      #      --disable-sc-7t5v0-gf180mcu --disable-sc-9t5v0-gf180mcu --disable-sram-gf180mcu \
      #      --disable-alpha-gf180mcu --disable-osu-sc-gf180mcu --disable-avalon-sc-gf180mcu \
      #      --disable-ocd-io-gf180mcu --disable-ocd-sram-gf180mcu

          # These are needed for a step in make
          #  --disable-klayout-sky130 --disable-precheck-sky130
          #
          #make
          #sudo make install
          #cd $HOME
      - name: Checkout dependencies
        shell: bash
        run: |
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          echo "/opt/eda/bin" >> $GITHUB_PATH
          export PATH=/opt/eda/bin:$HOME/.local/bin:$PATH
          python3 -m pip install cicconf

          echo -e "\nGDS2glTF:\n  remote: git@github.com:wulffern/GDS2glTF.git\n  revision: main" >> config.yaml

          cicconf --rundir ../ --config config.yaml clone --https

          python3 -m pip install -r ../GDS2glTF/requirements.txt
      - name: Install cicsim
        shell: bash
        run:  python3 -m pip install cicsim
      - name: Run docs
        shell: bash
        run: |
          export PDK_ROOT=/opt/pdk/share/pdk
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          echo "/opt/eda/bin" >> $GITHUB_PATH
          export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/eda/lib
          git config --global --add safe.directory `pwd`
          export PATH=/opt/eda/bin:$HOME/.local/bin:$PATH
          bash  ${GITHUB_ACTION_PATH}/gendoc
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./docs/
          destination: ./_site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
