name: Docs

on:
  workflow_call:

permissions:
  contents: read
  pages: write
  id-token: write


concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:

  build:
    runs-on: ubuntu-latest
    container:
      image: wulffern/aicex:26.04_0.1.8
      options: --user root
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: doc
        uses: npfe/jnw-actions/doc@643c2cebb5406c6c411ebf8eb917ef3cf100c334
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
