name: JNW_LVS

on:
  workflow_call:

jobs:
  lvs:
    runs-on: ubuntu-latest
    container:
      image: wulffern/aicex:26.04_0.1.8
      options: --user root
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run LVS
        uses: analogicus/jnw-actions/lvs@main
